
/**
 * @typedef {Object} BRAND
 * @property {string} logo - The logo of the brand.
 * @property {string} name - The name of the brand.
 * @property {number} visitors - The number of visitors to the brand.
 * @property {string} revenues - The revenue generated by the brand.
 * @property {number} sales - The number of sales made by the brand.
 * @property {number} conversion - The conversion rate for the brand.
 */